//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesObject.Entities.MetroMembershipEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberAdmin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MemberAdmin()
        {
            this.MemberPermissions = new HashSet<MemberPermission>();
        }
    
        public int ID { get; set; }
        public string NickName { get; set; }
        public string FullName { get; set; }
        public string Avatar { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string PasswordSalt { get; set; }
        public Nullable<bool> IsLockedOut { get; set; }
        public Nullable<System.DateTime> CreateDated { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public Nullable<System.DateTime> LastPasswordChangeDated { get; set; }
        public Nullable<System.DateTime> LastLogoutDate { get; set; }
        public Nullable<int> FailedPasswordAttempCount { get; set; }
        public Nullable<int> GroupID { get; set; }
        public string LastIPAddress { get; set; }
        public string LastAgent { get; set; }
        public string TokenID { get; set; }
        public Nullable<System.DateTime> TokenExp { get; set; }
        public Nullable<int> ChannelId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberPermission> MemberPermissions { get; set; }
        public virtual GroupMember GroupMember { get; set; }
    }
}
