//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesObject.Entities.MetroUserEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Association
    {
        public int AssociationID { get; set; }
        public Nullable<int> OwnerID { get; set; }
        public string OwnerNickName { get; set; }
        public string Name { get; set; }
        public string Slogan { get; set; }
        public string LocationOffline { get; set; }
        public string ImagePath { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string BoxLink { get; set; }
        public string DetailLink { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> Active { get; set; }
        public decimal AssCoin { get; set; }
        public Nullable<decimal> AssCoinCollect { get; set; }
        public int MemberBonus { get; set; }
        public string AssNameID { get; set; }
        public Nullable<bool> IsAwarded { get; set; }
        public string Introduction { get; set; }
        public string Regulation { get; set; }
        public Nullable<int> MaxLevel { get; set; }
        public string JoinCondition { get; set; }
        public Nullable<int> ChannelId { get; set; }
    }
}
