//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesObject.Entities.MetroUserEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssociationComment
    {
        public int AssCommentID { get; set; }
        public Nullable<int> AssociationID { get; set; }
        public string Comment { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CommentFor { get; set; }
        public bool IsRead { get; set; }
    }
}
