//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesObject.Entities.MetroUserEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssociationMember
    {
        public int AssociationID { get; set; }
        public int UserID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> IsOwner { get; set; }
        public string NickName { get; set; }
        public string Emotion { get; set; }
        public decimal ContCoin { get; set; }
        public bool IsSubOwner { get; set; }
        public Nullable<System.DateTime> ActiveDate { get; set; }
        public Nullable<System.DateTime> CreateDateSubOwner { get; set; }
        public decimal ContExp { get; set; }
        public Nullable<decimal> ContCoinSinceJoin { get; set; }
        public Nullable<decimal> ContExpSinceJoin { get; set; }
    }
}
