
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EntitiesObject.Entities.WebEntities
{

using System;
    using System.Collections.Generic;
    
public partial class Portfolio
{

    public int Id { get; set; }

    public string Name { get; set; }

    public string Avatar { get; set; }

    public string About { get; set; }

    public int CategoryId { get; set; }

    public string LinkWeb { get; set; }

    public string LinkProfile { get; set; }

    public string Language { get; set; }

}

}
