//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesObject.Entities.UserEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int UserID { get; set; }
        public Nullable<int> PubUserID { get; set; }
        public string Username { get; set; }
        public string DisplayName { get; set; }
        public string EmotionPath { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Token { get; set; }
        public Nullable<System.DateTime> TokenExpiredTime { get; set; }
        public Nullable<int> OpenProviderId { get; set; }
        public string OpenUserId { get; set; }
        public Nullable<int> PlatformId { get; set; }
        public string HardwareId { get; set; }
        public string PasswordSalt { get; set; }
        public Nullable<int> CampaignId { get; set; }
        public Nullable<int> ChannelId { get; set; }
        public string VersionGame { get; set; }
    }
}
