//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesObject.Entities.UserEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public int ArticleID { get; set; }
        public int AssociationID { get; set; }
        public int UserID { get; set; }
        public string TextID { get; set; }
        public string Title { get; set; }
        public string Abstract { get; set; }
        public string Body { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public int ViewCount { get; set; }
        public int CategoryID { get; set; }
        public int CommentCount { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> AdminStatus { get; set; }
        public string ImageLink { get; set; }
        public string ImageHome { get; set; }
        public bool IsCommented { get; set; }
        public int DomainID { get; set; }
        public int HotStatus { get; set; }
        public string ShortDescription { get; set; }
        public Nullable<int> DisplayTarget { get; set; }
        public Nullable<int> HotOrNew { get; set; }
        public Nullable<int> AdminID { get; set; }
        public Nullable<System.DateTime> PublicDate { get; set; }
        public Nullable<System.DateTime> HotExpire { get; set; }
        public Nullable<System.DateTime> NewExpire { get; set; }
        public Nullable<long> GroupID { get; set; }
    }
}
