//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesObject.Entities.UserEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardStock
    {
        public int ID { get; set; }
        public Nullable<int> ProviderId { get; set; }
        public Nullable<int> CardType { get; set; }
        public Nullable<int> Amount { get; set; }
        public string CardSeri { get; set; }
        public string CardPin { get; set; }
        public Nullable<bool> IsUse { get; set; }
        public Nullable<long> TransImportId { get; set; }
        public Nullable<long> TransExportId { get; set; }
        public Nullable<int> UserIdUsed { get; set; }
        public Nullable<System.DateTime> DateExport { get; set; }
        public Nullable<System.DateTime> DateImport { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string CardTypeName { get; set; }
    }
}
