//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesObject.Entities.UserEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FriendRelationship
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> UserFriendID { get; set; }
        public string OpenProviderID { get; set; }
        public string Description { get; set; }
        public Nullable<int> Relationship { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public Nullable<int> InviteType { get; set; }
    }
}
