//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesObject.Entities.UserEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogCardTran
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Serial { get; set; }
        public string PinCard { get; set; }
        public Nullable<int> CardType { get; set; }
        public Nullable<int> CardAmount { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> Result { get; set; }
        public Nullable<int> PartnerID { get; set; }
        public string PartnerTransID { get; set; }
        public string PartnerMessage { get; set; }
        public string IPAddress { get; set; }
        public Nullable<int> PlatformId { get; set; }
        public string DeviceID { get; set; }
        public Nullable<int> ChannelID { get; set; }
        public string VersionGame { get; set; }
    }
}
