//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesObject.Entities.UserEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfflineMessage
    {
        public int Id { get; set; }
        public Nullable<int> SenderId { get; set; }
        public Nullable<int> ReceiverId { get; set; }
        public string MessageContent { get; set; }
        public Nullable<int> MessageType { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public Nullable<System.DateTime> ReadDate { get; set; }
        public Nullable<int> Status { get; set; }
        public string IpAddress { get; set; }
        public Nullable<int> PlatformId { get; set; }
        public string HardwareId { get; set; }
        public Nullable<bool> IsSystem { get; set; }
        public Nullable<int> ParentId { get; set; }
    }
}
