//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesObject.Entities.UserEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentConfig
    {
        public int Id { get; set; }
        public Nullable<int> PaymentType { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Gold { get; set; }
        public Nullable<int> CardType { get; set; }
        public string Telco { get; set; }
        public Nullable<bool> IsEnable { get; set; }
        public string PacketName { get; set; }
        public Nullable<int> ChannelId { get; set; }
    }
}
