//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesObject.Entities.UserEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RankingDetail
    {
        public string RankingCode { get; set; }
        public System.DateTime DateReport { get; set; }
        public int UserId { get; set; }
        public string DisplayName { get; set; }
        public Nullable<int> OrderNo { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
