//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesObject.Entities.LogManagementEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LevelGameLog
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int Level { get; set; }
        public Nullable<int> OpenProviderId { get; set; }
    }
}
