//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesObject.Entities.LogManagementEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentLog
    {
        public long Id { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> PaymentType { get; set; }
        public Nullable<int> PlatformID { get; set; }
        public string IMEI { get; set; }
        public string HardwareID { get; set; }
        public string IPAddress { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> ObjectID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> ItemType { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
