//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesObject.Entities.LogManagementEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisterLog
    {
        public int Id { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public Nullable<int> PlatformID { get; set; }
        public Nullable<int> OpenProfiderID { get; set; }
        public string OpenUserID { get; set; }
        public string IMEI { get; set; }
        public string HardwareID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string IPAddress { get; set; }
        public string AppVersion { get; set; }
    }
}
