//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesObject.Entities.LogManagementEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RichGameLog
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<decimal> Coin { get; set; }
        public string DisplayName { get; set; }
        public string EmotionPath { get; set; }
        public Nullable<int> OpenProviderId { get; set; }
    }
}
