//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using EntitiesObject.Entities.EventEntities;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PxxxEventEntities : DbContext
    {
        public PxxxEventEntities()
            : base("name=PxxxEventEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<E1503_LogUserReceivedLiXi> E1503_LogUserReceivedLiXi { get; set; }
        public DbSet<E1503_UserWillReceivedLiXi> E1503_UserWillReceivedLiXi { get; set; }
        public DbSet<E1503_UserBlackList> E1503_UserBlackList { get; set; }
        public DbSet<EI1501_KhuyenMai_DaiLy_LogDeposit> EI1501_KhuyenMai_DaiLy_LogDeposit { get; set; }
        public DbSet<EI1501_KhuyenMai_DaiLy_GroupUser> EI1501_KhuyenMai_DaiLy_GroupUser { get; set; }
        public DbSet<E1504_TopBangHoiUser> E1504_TopBangHoiUser { get; set; }
        public DbSet<E1505_CodeUserEvent> E1505_CodeUserEvent { get; set; }
        public DbSet<E1506_UserTriAnVip> E1506_UserTriAnVip { get; set; }
        public DbSet<E1506_LogUserTriAnVip> E1506_LogUserTriAnVip { get; set; }
    
        public virtual int Out_E1503_LogUserReceivedLiXi_Insert(Nullable<int> userId, Nullable<System.DateTime> awardDate, Nullable<decimal> awardGold, Nullable<int> status, Nullable<int> clientTarget, string errorMessage, string userAgent, string ipAddress)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var awardDateParameter = awardDate.HasValue ?
                new ObjectParameter("AwardDate", awardDate) :
                new ObjectParameter("AwardDate", typeof(System.DateTime));
    
            var awardGoldParameter = awardGold.HasValue ?
                new ObjectParameter("AwardGold", awardGold) :
                new ObjectParameter("AwardGold", typeof(decimal));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(int));
    
            var clientTargetParameter = clientTarget.HasValue ?
                new ObjectParameter("ClientTarget", clientTarget) :
                new ObjectParameter("ClientTarget", typeof(int));
    
            var errorMessageParameter = errorMessage != null ?
                new ObjectParameter("ErrorMessage", errorMessage) :
                new ObjectParameter("ErrorMessage", typeof(string));
    
            var userAgentParameter = userAgent != null ?
                new ObjectParameter("UserAgent", userAgent) :
                new ObjectParameter("UserAgent", typeof(string));
    
            var ipAddressParameter = ipAddress != null ?
                new ObjectParameter("IpAddress", ipAddress) :
                new ObjectParameter("IpAddress", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Out_E1503_LogUserReceivedLiXi_Insert", userIdParameter, awardDateParameter, awardGoldParameter, statusParameter, clientTargetParameter, errorMessageParameter, userAgentParameter, ipAddressParameter);
        }
    
        public virtual ObjectResult<Out_E1503_UserWillReceivedLiXi_GetByUserId_Result> Out_E1503_UserWillReceivedLiXi_GetByUserId(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Out_E1503_UserWillReceivedLiXi_GetByUserId_Result>("Out_E1503_UserWillReceivedLiXi_GetByUserId", userIdParameter);
        }
    
        public virtual ObjectResult<Out_E1503_HistoryCoin_GetHistoryPlayGame_Result> Out_E1503_HistoryCoin_GetHistoryPlayGame(Nullable<int> userId, Nullable<System.DateTime> startTime, Nullable<System.DateTime> endTime, Nullable<int> top)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var startTimeParameter = startTime.HasValue ?
                new ObjectParameter("StartTime", startTime) :
                new ObjectParameter("StartTime", typeof(System.DateTime));
    
            var endTimeParameter = endTime.HasValue ?
                new ObjectParameter("EndTime", endTime) :
                new ObjectParameter("EndTime", typeof(System.DateTime));
    
            var topParameter = top.HasValue ?
                new ObjectParameter("Top", top) :
                new ObjectParameter("Top", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Out_E1503_HistoryCoin_GetHistoryPlayGame_Result>("Out_E1503_HistoryCoin_GetHistoryPlayGame", userIdParameter, startTimeParameter, endTimeParameter, topParameter);
        }
    
        public virtual ObjectResult<Out_E1504_TopBangHoiUser_GetTopBangHoiOrUser_Result> Out_E1504_TopBangHoiUser_GetTopBangHoiOrUser(Nullable<int> numTop, Nullable<int> logType)
        {
            var numTopParameter = numTop.HasValue ?
                new ObjectParameter("NumTop", numTop) :
                new ObjectParameter("NumTop", typeof(int));
    
            var logTypeParameter = logType.HasValue ?
                new ObjectParameter("LogType", logType) :
                new ObjectParameter("LogType", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Out_E1504_TopBangHoiUser_GetTopBangHoiOrUser_Result>("Out_E1504_TopBangHoiUser_GetTopBangHoiOrUser", numTopParameter, logTypeParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Out_E1505User_InsertCodeUser(Nullable<int> userId, string nickname, Nullable<int> convertRate, string code, Nullable<int> numberCode, Nullable<System.DateTime> dateBegin, Nullable<System.DateTime> dateEnd)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            var nicknameParameter = nickname != null ?
                new ObjectParameter("nickname", nickname) :
                new ObjectParameter("nickname", typeof(string));
    
            var convertRateParameter = convertRate.HasValue ?
                new ObjectParameter("convertRate", convertRate) :
                new ObjectParameter("convertRate", typeof(int));
    
            var codeParameter = code != null ?
                new ObjectParameter("code", code) :
                new ObjectParameter("code", typeof(string));
    
            var numberCodeParameter = numberCode.HasValue ?
                new ObjectParameter("numberCode", numberCode) :
                new ObjectParameter("numberCode", typeof(int));
    
            var dateBeginParameter = dateBegin.HasValue ?
                new ObjectParameter("dateBegin", dateBegin) :
                new ObjectParameter("dateBegin", typeof(System.DateTime));
    
            var dateEndParameter = dateEnd.HasValue ?
                new ObjectParameter("dateEnd", dateEnd) :
                new ObjectParameter("dateEnd", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Out_E1505User_InsertCodeUser", userIdParameter, nicknameParameter, convertRateParameter, codeParameter, numberCodeParameter, dateBeginParameter, dateEndParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Out_Event05CodeUserEvent_CountCodeAvaible(Nullable<int> userId, Nullable<int> convertRate, Nullable<System.DateTime> dateBegin, Nullable<System.DateTime> dateEnd)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            var convertRateParameter = convertRate.HasValue ?
                new ObjectParameter("convertRate", convertRate) :
                new ObjectParameter("convertRate", typeof(int));
    
            var dateBeginParameter = dateBegin.HasValue ?
                new ObjectParameter("dateBegin", dateBegin) :
                new ObjectParameter("dateBegin", typeof(System.DateTime));
    
            var dateEndParameter = dateEnd.HasValue ?
                new ObjectParameter("dateEnd", dateEnd) :
                new ObjectParameter("dateEnd", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Out_Event05CodeUserEvent_CountCodeAvaible", userIdParameter, convertRateParameter, dateBeginParameter, dateEndParameter);
        }
    
        public virtual ObjectResult<Out_E1505CodeUserEvent_GetCodeUser_Result> Out_E1505CodeUserEvent_GetCodeUser(Nullable<int> userId, Nullable<System.DateTime> dateBegin, Nullable<System.DateTime> dateEnd, Nullable<int> pageNumber, Nullable<int> pageSize)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            var dateBeginParameter = dateBegin.HasValue ?
                new ObjectParameter("dateBegin", dateBegin) :
                new ObjectParameter("dateBegin", typeof(System.DateTime));
    
            var dateEndParameter = dateEnd.HasValue ?
                new ObjectParameter("dateEnd", dateEnd) :
                new ObjectParameter("dateEnd", typeof(System.DateTime));
    
            var pageNumberParameter = pageNumber.HasValue ?
                new ObjectParameter("PageNumber", pageNumber) :
                new ObjectParameter("PageNumber", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Out_E1505CodeUserEvent_GetCodeUser_Result>("Out_E1505CodeUserEvent_GetCodeUser", userIdParameter, dateBeginParameter, dateEndParameter, pageNumberParameter, pageSizeParameter);
        }
    
        public virtual ObjectResult<Out_Event_VuaTaiXiu_GetTop_Result> Out_Event_VuaTaiXiu_GetTop(Nullable<int> numberTop)
        {
            var numberTopParameter = numberTop.HasValue ?
                new ObjectParameter("NumberTop", numberTop) :
                new ObjectParameter("NumberTop", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Out_Event_VuaTaiXiu_GetTop_Result>("Out_Event_VuaTaiXiu_GetTop", numberTopParameter);
        }
    
        public virtual ObjectResult<Out_E1507_GetConfigVuaTaiXiu_Result> Out_E1507_GetConfigVuaTaiXiu(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Out_E1507_GetConfigVuaTaiXiu_Result>("Out_E1507_GetConfigVuaTaiXiu", idParameter);
        }
    
        public virtual ObjectResult<Out_E1504_TopBangHoiUser_GetTotalGold_Result> Out_E1504_TopBangHoiUser_GetTotalGold(Nullable<int> assIdChampion, Nullable<int> logType)
        {
            var assIdChampionParameter = assIdChampion.HasValue ?
                new ObjectParameter("AssIdChampion", assIdChampion) :
                new ObjectParameter("AssIdChampion", typeof(int));
    
            var logTypeParameter = logType.HasValue ?
                new ObjectParameter("logType", logType) :
                new ObjectParameter("logType", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Out_E1504_TopBangHoiUser_GetTotalGold_Result>("Out_E1504_TopBangHoiUser_GetTotalGold", assIdChampionParameter, logTypeParameter);
        }
    
        public virtual ObjectResult<Out_E1504_TopBangHoiUser_GetTopDongGopChiTiet_Result> Out_E1504_TopBangHoiUser_GetTopDongGopChiTiet(Nullable<int> assId, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, Nullable<int> numberTop)
        {
            var assIdParameter = assId.HasValue ?
                new ObjectParameter("AssId", assId) :
                new ObjectParameter("AssId", typeof(int));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var numberTopParameter = numberTop.HasValue ?
                new ObjectParameter("NumberTop", numberTop) :
                new ObjectParameter("NumberTop", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Out_E1504_TopBangHoiUser_GetTopDongGopChiTiet_Result>("Out_E1504_TopBangHoiUser_GetTopDongGopChiTiet", assIdParameter, startDateParameter, endDateParameter, numberTopParameter);
        }
    }
}
