//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using EntitiesObject.Entities.EventManagement;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EventManagementEntities : DbContext
    {
        public EventManagementEntities()
            : base("name=EventManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EventPromotion> EventPromotions { get; set; }
        public virtual DbSet<TMission_Top> TMission_Top { get; set; }
        public virtual DbSet<E1605_AwardMakeFriend> E1605_AwardMakeFriend { get; set; }
    
        public virtual ObjectResult<Out_EventPromotion_GetInfo_Result> Out_EventPromotion_GetInfo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Out_EventPromotion_GetInfo_Result>("Out_EventPromotion_GetInfo");
        }
    
        public virtual ObjectResult<Out_EventPromotion_GetInfoDetails_Result> Out_EventPromotion_GetInfoDetails(Nullable<int> articleId)
        {
            var articleIdParameter = articleId.HasValue ?
                new ObjectParameter("ArticleId", articleId) :
                new ObjectParameter("ArticleId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Out_EventPromotion_GetInfoDetails_Result>("Out_EventPromotion_GetInfoDetails", articleIdParameter);
        }
    
        public virtual ObjectResult<Out_TMission_Top_GetTop_Result> Out_TMission_Top_GetTop(Nullable<int> top, Nullable<System.DateTime> date)
        {
            var topParameter = top.HasValue ?
                new ObjectParameter("Top", top) :
                new ObjectParameter("Top", typeof(int));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Out_TMission_Top_GetTop_Result>("Out_TMission_Top_GetTop", topParameter, dateParameter);
        }
    
        public virtual ObjectResult<Out_E1602TopUserWin_GetByDate_Result> Out_E1602TopUserWin_GetByDate(Nullable<System.DateTime> dateReport, Nullable<int> top)
        {
            var dateReportParameter = dateReport.HasValue ?
                new ObjectParameter("DateReport", dateReport) :
                new ObjectParameter("DateReport", typeof(System.DateTime));
    
            var topParameter = top.HasValue ?
                new ObjectParameter("Top", top) :
                new ObjectParameter("Top", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Out_E1602TopUserWin_GetByDate_Result>("Out_E1602TopUserWin_GetByDate", dateReportParameter, topParameter);
        }
    
        public virtual int Out_E1605_AwardMakeFriend_Add(Nullable<int> userId, Nullable<int> userFriendId, Nullable<decimal> goldAward, string description)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var userFriendIdParameter = userFriendId.HasValue ?
                new ObjectParameter("UserFriendId", userFriendId) :
                new ObjectParameter("UserFriendId", typeof(int));
    
            var goldAwardParameter = goldAward.HasValue ?
                new ObjectParameter("GoldAward", goldAward) :
                new ObjectParameter("GoldAward", typeof(decimal));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Out_E1605_AwardMakeFriend_Add", userIdParameter, userFriendIdParameter, goldAwardParameter, descriptionParameter);
        }
    
        public virtual int Out_E1605_AwardMakeFriend_CheckExist(Nullable<int> userId, Nullable<int> userFriendId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var userFriendIdParameter = userFriendId.HasValue ?
                new ObjectParameter("UserFriendId", userFriendId) :
                new ObjectParameter("UserFriendId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Out_E1605_AwardMakeFriend_CheckExist", userIdParameter, userFriendIdParameter);
        }
    
        public virtual ObjectResult<Out_EventPromotion_GetInfo_RunOn_Result> Out_EventPromotion_GetInfo_RunOn(Nullable<int> runOn)
        {
            var runOnParameter = runOn.HasValue ?
                new ObjectParameter("RunOn", runOn) :
                new ObjectParameter("RunOn", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Out_EventPromotion_GetInfo_RunOn_Result>("Out_EventPromotion_GetInfo_RunOn", runOnParameter);
        }
    
        public virtual ObjectResult<INS_Report_E1606_UserShootFish_GetDate_Result> INS_Report_E1606_UserShootFish_GetDate(Nullable<int> top, Nullable<System.DateTime> date)
        {
            var topParameter = top.HasValue ?
                new ObjectParameter("top", top) :
                new ObjectParameter("top", typeof(int));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<INS_Report_E1606_UserShootFish_GetDate_Result>("INS_Report_E1606_UserShootFish_GetDate", topParameter, dateParameter);
        }
    
        public virtual ObjectResult<Out_Report_E1606_UserShootFish_GetDate_Result> Out_Report_E1606_UserShootFish_GetDate(Nullable<int> top, Nullable<System.DateTime> date)
        {
            var topParameter = top.HasValue ?
                new ObjectParameter("top", top) :
                new ObjectParameter("top", typeof(int));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("Date", date) :
                new ObjectParameter("Date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Out_Report_E1606_UserShootFish_GetDate_Result>("Out_Report_E1606_UserShootFish_GetDate", topParameter, dateParameter);
        }
    
        public virtual ObjectResult<Out_FishCollection_AcchiveUser_Result> Out_FishCollection_AcchiveUser(Nullable<int> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Out_FishCollection_AcchiveUser_Result>("Out_FishCollection_AcchiveUser", useridParameter);
        }
    
        public virtual ObjectResult<Ins_FishCollection_GetTop_Result> Ins_FishCollection_GetTop(Nullable<int> top)
        {
            var topParameter = top.HasValue ?
                new ObjectParameter("top", top) :
                new ObjectParameter("top", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Ins_FishCollection_GetTop_Result>("Ins_FishCollection_GetTop", topParameter);
        }
    
        public virtual ObjectResult<Out_E1607_TopFriendWinGold_GetTop_Result> Out_E1607_TopFriendWinGold_GetTop()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Out_E1607_TopFriendWinGold_GetTop_Result>("Out_E1607_TopFriendWinGold_GetTop");
        }
    
        public virtual ObjectResult<Out_E1607_TopFriendWinGold_Archives_Result> Out_E1607_TopFriendWinGold_Archives(Nullable<int> userID, Nullable<System.DateTime> dateBegin, Nullable<System.DateTime> dateEnd)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var dateBeginParameter = dateBegin.HasValue ?
                new ObjectParameter("dateBegin", dateBegin) :
                new ObjectParameter("dateBegin", typeof(System.DateTime));
    
            var dateEndParameter = dateEnd.HasValue ?
                new ObjectParameter("dateEnd", dateEnd) :
                new ObjectParameter("dateEnd", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Out_E1607_TopFriendWinGold_Archives_Result>("Out_E1607_TopFriendWinGold_Archives", userIDParameter, dateBeginParameter, dateEndParameter);
        }
    
        public virtual ObjectResult<Out_EventPromotion_GetEventByCode_Result> Out_EventPromotion_GetEventByCode(string key)
        {
            var keyParameter = key != null ?
                new ObjectParameter("key", key) :
                new ObjectParameter("key", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Out_EventPromotion_GetEventByCode_Result>("Out_EventPromotion_GetEventByCode", keyParameter);
        }
    
        public virtual ObjectResult<Ins_E1607_TopManyFriend_GetTopFriendFacebook_Result> Ins_E1607_TopManyFriend_GetTopFriendFacebook(Nullable<int> top)
        {
            var topParameter = top.HasValue ?
                new ObjectParameter("Top", top) :
                new ObjectParameter("Top", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Ins_E1607_TopManyFriend_GetTopFriendFacebook_Result>("Ins_E1607_TopManyFriend_GetTopFriendFacebook", topParameter);
        }
    
        public virtual ObjectResult<Ins_E1607_TopManyFriend_GetTopFriendFacebookOfUser_Result> Ins_E1607_TopManyFriend_GetTopFriendFacebookOfUser(Nullable<int> userID, Nullable<int> pageSize, Nullable<int> position)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var positionParameter = position.HasValue ?
                new ObjectParameter("Position", position) :
                new ObjectParameter("Position", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Ins_E1607_TopManyFriend_GetTopFriendFacebookOfUser_Result>("Ins_E1607_TopManyFriend_GetTopFriendFacebookOfUser", userIDParameter, pageSizeParameter, positionParameter);
        }
    
        public virtual ObjectResult<Out_E1607_TopGoldFriend_GetData_Result> Out_E1607_TopGoldFriend_GetData(Nullable<int> position, Nullable<int> pageSize, ObjectParameter totalRow)
        {
            var positionParameter = position.HasValue ?
                new ObjectParameter("Position", position) :
                new ObjectParameter("Position", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Out_E1607_TopGoldFriend_GetData_Result>("Out_E1607_TopGoldFriend_GetData", positionParameter, pageSizeParameter, totalRow);
        }
    
        public virtual ObjectResult<Out_FriendRelationship_TopFriendFbGoldMax_Result> Out_FriendRelationship_TopFriendFbGoldMax(Nullable<int> userId, Nullable<int> position, Nullable<int> pageSize, ObjectParameter totalRow)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var positionParameter = position.HasValue ?
                new ObjectParameter("Position", position) :
                new ObjectParameter("Position", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Out_FriendRelationship_TopFriendFbGoldMax_Result>("Out_FriendRelationship_TopFriendFbGoldMax", userIdParameter, positionParameter, pageSizeParameter, totalRow);
        }
    
        public virtual ObjectResult<Ins_EventPromotion_GetEventById_Result> Ins_EventPromotion_GetEventById(Nullable<int> eventId)
        {
            var eventIdParameter = eventId.HasValue ?
                new ObjectParameter("EventId", eventId) :
                new ObjectParameter("EventId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Ins_EventPromotion_GetEventById_Result>("Ins_EventPromotion_GetEventById", eventIdParameter);
        }
    
        public virtual ObjectResult<Out_E1602TopUserWin_GetTopByDate_Result> Out_E1602TopUserWin_GetTopByDate(Nullable<int> top)
        {
            var topParameter = top.HasValue ?
                new ObjectParameter("Top", top) :
                new ObjectParameter("Top", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Out_E1602TopUserWin_GetTopByDate_Result>("Out_E1602TopUserWin_GetTopByDate", topParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Out_CheckKhuyenMaiNapTien_Valid(Nullable<int> soluongthe, Nullable<int> minamount, Nullable<int> maxamount, Nullable<int> userid, Nullable<int> amount)
        {
            var soluongtheParameter = soluongthe.HasValue ?
                new ObjectParameter("soluongthe", soluongthe) :
                new ObjectParameter("soluongthe", typeof(int));
    
            var minamountParameter = minamount.HasValue ?
                new ObjectParameter("minamount", minamount) :
                new ObjectParameter("minamount", typeof(int));
    
            var maxamountParameter = maxamount.HasValue ?
                new ObjectParameter("maxamount", maxamount) :
                new ObjectParameter("maxamount", typeof(int));
    
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            var amountParameter = amount.HasValue ?
                new ObjectParameter("amount", amount) :
                new ObjectParameter("amount", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Out_CheckKhuyenMaiNapTien_Valid", soluongtheParameter, minamountParameter, maxamountParameter, useridParameter, amountParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Out_E1610_KhuyenMaiNapTheLanDau_Insert(Nullable<int> userid, Nullable<int> chanelid, string iprequest, Nullable<int> platformid, string gameversion, Nullable<int> amount)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            var chanelidParameter = chanelid.HasValue ?
                new ObjectParameter("chanelid", chanelid) :
                new ObjectParameter("chanelid", typeof(int));
    
            var iprequestParameter = iprequest != null ?
                new ObjectParameter("iprequest", iprequest) :
                new ObjectParameter("iprequest", typeof(string));
    
            var platformidParameter = platformid.HasValue ?
                new ObjectParameter("platformid", platformid) :
                new ObjectParameter("platformid", typeof(int));
    
            var gameversionParameter = gameversion != null ?
                new ObjectParameter("gameversion", gameversion) :
                new ObjectParameter("gameversion", typeof(string));
    
            var amountParameter = amount.HasValue ?
                new ObjectParameter("amount", amount) :
                new ObjectParameter("amount", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Out_E1610_KhuyenMaiNapTheLanDau_Insert", useridParameter, chanelidParameter, iprequestParameter, platformidParameter, gameversionParameter, amountParameter);
        }
    
        public virtual ObjectResult<Out_A_TPlayGame_ListHitFish_ByUser_EventBanCa_Result> Out_A_TPlayGame_ListHitFish_ByUser_EventBanCa(Nullable<int> rowStart, Nullable<int> rowEnd, Nullable<int> top, ObjectParameter totalRow)
        {
            var rowStartParameter = rowStart.HasValue ?
                new ObjectParameter("RowStart", rowStart) :
                new ObjectParameter("RowStart", typeof(int));
    
            var rowEndParameter = rowEnd.HasValue ?
                new ObjectParameter("RowEnd", rowEnd) :
                new ObjectParameter("RowEnd", typeof(int));
    
            var topParameter = top.HasValue ?
                new ObjectParameter("Top", top) :
                new ObjectParameter("Top", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Out_A_TPlayGame_ListHitFish_ByUser_EventBanCa_Result>("Out_A_TPlayGame_ListHitFish_ByUser_EventBanCa", rowStartParameter, rowEndParameter, topParameter, totalRow);
        }
    
        public virtual ObjectResult<Nullable<int>> Out_E1612_KhuyenMaiTheoMenhGia_Insert(Nullable<int> userid, Nullable<int> chanelid, Nullable<int> platformid, string gameversion, Nullable<int> amount, Nullable<int> cardtype, Nullable<double> percent, string ipRequest)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            var chanelidParameter = chanelid.HasValue ?
                new ObjectParameter("chanelid", chanelid) :
                new ObjectParameter("chanelid", typeof(int));
    
            var platformidParameter = platformid.HasValue ?
                new ObjectParameter("platformid", platformid) :
                new ObjectParameter("platformid", typeof(int));
    
            var gameversionParameter = gameversion != null ?
                new ObjectParameter("gameversion", gameversion) :
                new ObjectParameter("gameversion", typeof(string));
    
            var amountParameter = amount.HasValue ?
                new ObjectParameter("amount", amount) :
                new ObjectParameter("amount", typeof(int));
    
            var cardtypeParameter = cardtype.HasValue ?
                new ObjectParameter("cardtype", cardtype) :
                new ObjectParameter("cardtype", typeof(int));
    
            var percentParameter = percent.HasValue ?
                new ObjectParameter("percent", percent) :
                new ObjectParameter("percent", typeof(double));
    
            var ipRequestParameter = ipRequest != null ?
                new ObjectParameter("ipRequest", ipRequest) :
                new ObjectParameter("ipRequest", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Out_E1612_KhuyenMaiTheoMenhGia_Insert", useridParameter, chanelidParameter, platformidParameter, gameversionParameter, amountParameter, cardtypeParameter, percentParameter, ipRequestParameter);
        }
    
        public virtual ObjectResult<Out_EventPromotion_GetEventRunningByType_Result> Out_EventPromotion_GetEventRunningByType(Nullable<int> type)
        {
            var typeParameter = type.HasValue ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Out_EventPromotion_GetEventRunningByType_Result>("Out_EventPromotion_GetEventRunningByType", typeParameter);
        }
    
        public virtual ObjectResult<Out_E1604_TopAttackBoss_GetDataTop_Result> Out_E1604_TopAttackBoss_GetDataTop(Nullable<int> top, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var topParameter = top.HasValue ?
                new ObjectParameter("top", top) :
                new ObjectParameter("top", typeof(int));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Out_E1604_TopAttackBoss_GetDataTop_Result>("Out_E1604_TopAttackBoss_GetDataTop", topParameter, fromDateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<Out_LogUserRecieveLuckyEveryday_GetFullDataForAPI_Result> Out_LogUserRecieveLuckyEveryday_GetFullDataForAPI()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Out_LogUserRecieveLuckyEveryday_GetFullDataForAPI_Result>("Out_LogUserRecieveLuckyEveryday_GetFullDataForAPI");
        }
    
        public virtual ObjectResult<Out_E1609_LogConfigLuckyEveryday_GetDateEventEveryDay_Result> Out_E1609_LogConfigLuckyEveryday_GetDateEventEveryDay()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Out_E1609_LogConfigLuckyEveryday_GetDateEventEveryDay_Result>("Out_E1609_LogConfigLuckyEveryday_GetDateEventEveryDay");
        }
    
        public virtual ObjectResult<Out_LogUserRecieveLuckyEveryday_GetFullDataForAPI_ByDate_Result> Out_LogUserRecieveLuckyEveryday_GetFullDataForAPI_ByDate(Nullable<System.DateTime> dateReport, Nullable<int> periodOfTime, Nullable<int> rowBegin, Nullable<int> rowEnd)
        {
            var dateReportParameter = dateReport.HasValue ?
                new ObjectParameter("DateReport", dateReport) :
                new ObjectParameter("DateReport", typeof(System.DateTime));
    
            var periodOfTimeParameter = periodOfTime.HasValue ?
                new ObjectParameter("PeriodOfTime", periodOfTime) :
                new ObjectParameter("PeriodOfTime", typeof(int));
    
            var rowBeginParameter = rowBegin.HasValue ?
                new ObjectParameter("RowBegin", rowBegin) :
                new ObjectParameter("RowBegin", typeof(int));
    
            var rowEndParameter = rowEnd.HasValue ?
                new ObjectParameter("RowEnd", rowEnd) :
                new ObjectParameter("RowEnd", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Out_LogUserRecieveLuckyEveryday_GetFullDataForAPI_ByDate_Result>("Out_LogUserRecieveLuckyEveryday_GetFullDataForAPI_ByDate", dateReportParameter, periodOfTimeParameter, rowBeginParameter, rowEndParameter);
        }
    }
}
