//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using EntitiesObject.Entities.MetroMembershipEntities;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MetroMembershipEntities : DbContext
    {
        public MetroMembershipEntities()
            : base("name=MetroMembershipEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActionAdmin> ActionAdmins { get; set; }
        public virtual DbSet<AdminConfigData> AdminConfigDatas { get; set; }
        public virtual DbSet<Channel> Channels { get; set; }
        public virtual DbSet<GroupMember> GroupMembers { get; set; }
        public virtual DbSet<GroupPermission> GroupPermissions { get; set; }
        public virtual DbSet<LogActionAdmin> LogActionAdmins { get; set; }
        public virtual DbSet<MemberAdmin> MemberAdmins { get; set; }
        public virtual DbSet<MemberPermission> MemberPermissions { get; set; }
        public virtual DbSet<PageFunction> PageFunctions { get; set; }
        public virtual DbSet<TempTable> TempTables { get; set; }
    
        public virtual ObjectResult<Ins_ActionAdmin_GetAll_Result> Ins_ActionAdmin_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Ins_ActionAdmin_GetAll_Result>("Ins_ActionAdmin_GetAll");
        }
    
        public virtual ObjectResult<Ins_AdminConfigData_getConfigByAdminID_Result> Ins_AdminConfigData_getConfigByAdminID(Nullable<int> adminID, Nullable<int> keyID)
        {
            var adminIDParameter = adminID.HasValue ?
                new ObjectParameter("adminID", adminID) :
                new ObjectParameter("adminID", typeof(int));
    
            var keyIDParameter = keyID.HasValue ?
                new ObjectParameter("keyID", keyID) :
                new ObjectParameter("keyID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Ins_AdminConfigData_getConfigByAdminID_Result>("Ins_AdminConfigData_getConfigByAdminID", adminIDParameter, keyIDParameter);
        }
    
        public virtual int Ins_AdminConfigData_insertConfigData(Nullable<int> adminID, Nullable<int> keyID, string config, string note)
        {
            var adminIDParameter = adminID.HasValue ?
                new ObjectParameter("adminID", adminID) :
                new ObjectParameter("adminID", typeof(int));
    
            var keyIDParameter = keyID.HasValue ?
                new ObjectParameter("keyID", keyID) :
                new ObjectParameter("keyID", typeof(int));
    
            var configParameter = config != null ?
                new ObjectParameter("config", config) :
                new ObjectParameter("config", typeof(string));
    
            var noteParameter = note != null ?
                new ObjectParameter("note", note) :
                new ObjectParameter("note", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Ins_AdminConfigData_insertConfigData", adminIDParameter, keyIDParameter, configParameter, noteParameter);
        }
    
        public virtual ObjectResult<Ins_Channel_GetListChannelByParentId_Result> Ins_Channel_GetListChannelByParentId(Nullable<int> channelId)
        {
            var channelIdParameter = channelId.HasValue ?
                new ObjectParameter("channelId", channelId) :
                new ObjectParameter("channelId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Ins_Channel_GetListChannelByParentId_Result>("Ins_Channel_GetListChannelByParentId", channelIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Ins_GroupMember_AddAdminGroupManager(string groupName, Nullable<bool> visible)
        {
            var groupNameParameter = groupName != null ?
                new ObjectParameter("GroupName", groupName) :
                new ObjectParameter("GroupName", typeof(string));
    
            var visibleParameter = visible.HasValue ?
                new ObjectParameter("Visible", visible) :
                new ObjectParameter("Visible", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Ins_GroupMember_AddAdminGroupManager", groupNameParameter, visibleParameter);
        }
    
        public virtual ObjectResult<Ins_GroupMember_AdminGroupManagerGetInfoByID_Result> Ins_GroupMember_AdminGroupManagerGetInfoByID(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Ins_GroupMember_AdminGroupManagerGetInfoByID_Result>("Ins_GroupMember_AdminGroupManagerGetInfoByID", iDParameter);
        }
    
        public virtual ObjectResult<Ins_GroupMember_GetAllGroupMemberAdmin_Result> Ins_GroupMember_GetAllGroupMemberAdmin()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Ins_GroupMember_GetAllGroupMemberAdmin_Result>("Ins_GroupMember_GetAllGroupMemberAdmin");
        }
    
        public virtual ObjectResult<Ins_GroupMember_GetListGroup_Result> Ins_GroupMember_GetListGroup(Nullable<int> rowStart, Nullable<int> rowEnd, Nullable<int> orderBy, Nullable<int> orderDirection, ObjectParameter totalRow)
        {
            var rowStartParameter = rowStart.HasValue ?
                new ObjectParameter("RowStart", rowStart) :
                new ObjectParameter("RowStart", typeof(int));
    
            var rowEndParameter = rowEnd.HasValue ?
                new ObjectParameter("RowEnd", rowEnd) :
                new ObjectParameter("RowEnd", typeof(int));
    
            var orderByParameter = orderBy.HasValue ?
                new ObjectParameter("OrderBy", orderBy) :
                new ObjectParameter("OrderBy", typeof(int));
    
            var orderDirectionParameter = orderDirection.HasValue ?
                new ObjectParameter("OrderDirection", orderDirection) :
                new ObjectParameter("OrderDirection", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Ins_GroupMember_GetListGroup_Result>("Ins_GroupMember_GetListGroup", rowStartParameter, rowEndParameter, orderByParameter, orderDirectionParameter, totalRow);
        }
    
        public virtual ObjectResult<Nullable<int>> Ins_GroupMember_UpdateAdminGroupManager(Nullable<int> iD, string groupName, Nullable<bool> visible)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var groupNameParameter = groupName != null ?
                new ObjectParameter("GroupName", groupName) :
                new ObjectParameter("GroupName", typeof(string));
    
            var visibleParameter = visible.HasValue ?
                new ObjectParameter("Visible", visible) :
                new ObjectParameter("Visible", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Ins_GroupMember_UpdateAdminGroupManager", iDParameter, groupNameParameter, visibleParameter);
        }
    
        public virtual int Ins_GroupPermission_CloneGroup(Nullable<int> groupID, Nullable<int> userID)
        {
            var groupIDParameter = groupID.HasValue ?
                new ObjectParameter("GroupID", groupID) :
                new ObjectParameter("GroupID", typeof(int));
    
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Ins_GroupPermission_CloneGroup", groupIDParameter, userIDParameter);
        }
    
        public virtual int Ins_GroupPermission_UpdateAndInsertGroupPermission(Nullable<int> pageID, Nullable<int> groupID, Nullable<int> rules, Nullable<int> check)
        {
            var pageIDParameter = pageID.HasValue ?
                new ObjectParameter("PageID", pageID) :
                new ObjectParameter("PageID", typeof(int));
    
            var groupIDParameter = groupID.HasValue ?
                new ObjectParameter("GroupID", groupID) :
                new ObjectParameter("GroupID", typeof(int));
    
            var rulesParameter = rules.HasValue ?
                new ObjectParameter("Rules", rules) :
                new ObjectParameter("Rules", typeof(int));
    
            var checkParameter = check.HasValue ?
                new ObjectParameter("Check", check) :
                new ObjectParameter("Check", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Ins_GroupPermission_UpdateAndInsertGroupPermission", pageIDParameter, groupIDParameter, rulesParameter, checkParameter);
        }
    
        public virtual int Ins_GroupPermission_UpdateAndInsertUserPermission(Nullable<int> pageID, Nullable<int> userID, Nullable<int> rules, Nullable<int> check)
        {
            var pageIDParameter = pageID.HasValue ?
                new ObjectParameter("PageID", pageID) :
                new ObjectParameter("PageID", typeof(int));
    
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var rulesParameter = rules.HasValue ?
                new ObjectParameter("Rules", rules) :
                new ObjectParameter("Rules", typeof(int));
    
            var checkParameter = check.HasValue ?
                new ObjectParameter("Check", check) :
                new ObjectParameter("Check", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Ins_GroupPermission_UpdateAndInsertUserPermission", pageIDParameter, userIDParameter, rulesParameter, checkParameter);
        }
    
        public virtual ObjectResult<Ins_LogActionAdmin_GetByAdminName_Result> Ins_LogActionAdmin_GetByAdminName(string adminName, Nullable<int> actionId, Nullable<int> rowStart, Nullable<int> rowEnd, Nullable<int> orderBy, Nullable<bool> isDescending, ObjectParameter totalRow)
        {
            var adminNameParameter = adminName != null ?
                new ObjectParameter("AdminName", adminName) :
                new ObjectParameter("AdminName", typeof(string));
    
            var actionIdParameter = actionId.HasValue ?
                new ObjectParameter("ActionId", actionId) :
                new ObjectParameter("ActionId", typeof(int));
    
            var rowStartParameter = rowStart.HasValue ?
                new ObjectParameter("RowStart", rowStart) :
                new ObjectParameter("RowStart", typeof(int));
    
            var rowEndParameter = rowEnd.HasValue ?
                new ObjectParameter("RowEnd", rowEnd) :
                new ObjectParameter("RowEnd", typeof(int));
    
            var orderByParameter = orderBy.HasValue ?
                new ObjectParameter("OrderBy", orderBy) :
                new ObjectParameter("OrderBy", typeof(int));
    
            var isDescendingParameter = isDescending.HasValue ?
                new ObjectParameter("IsDescending", isDescending) :
                new ObjectParameter("IsDescending", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Ins_LogActionAdmin_GetByAdminName_Result>("Ins_LogActionAdmin_GetByAdminName", adminNameParameter, actionIdParameter, rowStartParameter, rowEndParameter, orderByParameter, isDescendingParameter, totalRow);
        }
    
        public virtual ObjectResult<Nullable<int>> Ins_LogActionAdmin_InsertLog(Nullable<int> adminId, Nullable<int> actionId, string actionName, string objectId, string description, string beforeConfig, string ipAddress, string userAgent)
        {
            var adminIdParameter = adminId.HasValue ?
                new ObjectParameter("AdminId", adminId) :
                new ObjectParameter("AdminId", typeof(int));
    
            var actionIdParameter = actionId.HasValue ?
                new ObjectParameter("ActionId", actionId) :
                new ObjectParameter("ActionId", typeof(int));
    
            var actionNameParameter = actionName != null ?
                new ObjectParameter("ActionName", actionName) :
                new ObjectParameter("ActionName", typeof(string));
    
            var objectIdParameter = objectId != null ?
                new ObjectParameter("ObjectId", objectId) :
                new ObjectParameter("ObjectId", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var beforeConfigParameter = beforeConfig != null ?
                new ObjectParameter("BeforeConfig", beforeConfig) :
                new ObjectParameter("BeforeConfig", typeof(string));
    
            var ipAddressParameter = ipAddress != null ?
                new ObjectParameter("IpAddress", ipAddress) :
                new ObjectParameter("IpAddress", typeof(string));
    
            var userAgentParameter = userAgent != null ?
                new ObjectParameter("UserAgent", userAgent) :
                new ObjectParameter("UserAgent", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Ins_LogActionAdmin_InsertLog", adminIdParameter, actionIdParameter, actionNameParameter, objectIdParameter, descriptionParameter, beforeConfigParameter, ipAddressParameter, userAgentParameter);
        }
    
        public virtual ObjectResult<Ins_MemberAdmin_checkLogin_Result> Ins_MemberAdmin_checkLogin(string userName, string tokenID)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("userName", userName) :
                new ObjectParameter("userName", typeof(string));
    
            var tokenIDParameter = tokenID != null ?
                new ObjectParameter("tokenID", tokenID) :
                new ObjectParameter("tokenID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Ins_MemberAdmin_checkLogin_Result>("Ins_MemberAdmin_checkLogin", userNameParameter, tokenIDParameter);
        }
    
        public virtual ObjectResult<Ins_MemberAdmin_getInfoMemberAdmin_Result> Ins_MemberAdmin_getInfoMemberAdmin(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Ins_MemberAdmin_getInfoMemberAdmin_Result>("Ins_MemberAdmin_getInfoMemberAdmin", userIdParameter);
        }
    
        public virtual ObjectResult<Ins_MemberAdmin_getListMember_Result> Ins_MemberAdmin_getListMember(string keySearch, Nullable<int> pageNumber, Nullable<int> pageSize)
        {
            var keySearchParameter = keySearch != null ?
                new ObjectParameter("keySearch", keySearch) :
                new ObjectParameter("keySearch", typeof(string));
    
            var pageNumberParameter = pageNumber.HasValue ?
                new ObjectParameter("PageNumber", pageNumber) :
                new ObjectParameter("PageNumber", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Ins_MemberAdmin_getListMember_Result>("Ins_MemberAdmin_getListMember", keySearchParameter, pageNumberParameter, pageSizeParameter);
        }
    
        public virtual ObjectResult<Ins_MemberAdmin_GetListMemberByGroupID_Result> Ins_MemberAdmin_GetListMemberByGroupID(Nullable<int> groupID, Nullable<int> visible, Nullable<int> rowStart, Nullable<int> rowEnd, Nullable<int> orderBy, Nullable<int> orderDirection, ObjectParameter totalRow)
        {
            var groupIDParameter = groupID.HasValue ?
                new ObjectParameter("GroupID", groupID) :
                new ObjectParameter("GroupID", typeof(int));
    
            var visibleParameter = visible.HasValue ?
                new ObjectParameter("Visible", visible) :
                new ObjectParameter("Visible", typeof(int));
    
            var rowStartParameter = rowStart.HasValue ?
                new ObjectParameter("RowStart", rowStart) :
                new ObjectParameter("RowStart", typeof(int));
    
            var rowEndParameter = rowEnd.HasValue ?
                new ObjectParameter("RowEnd", rowEnd) :
                new ObjectParameter("RowEnd", typeof(int));
    
            var orderByParameter = orderBy.HasValue ?
                new ObjectParameter("OrderBy", orderBy) :
                new ObjectParameter("OrderBy", typeof(int));
    
            var orderDirectionParameter = orderDirection.HasValue ?
                new ObjectParameter("OrderDirection", orderDirection) :
                new ObjectParameter("OrderDirection", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Ins_MemberAdmin_GetListMemberByGroupID_Result>("Ins_MemberAdmin_GetListMemberByGroupID", groupIDParameter, visibleParameter, rowStartParameter, rowEndParameter, orderByParameter, orderDirectionParameter, totalRow);
        }
    
        public virtual ObjectResult<Ins_MemberAdmin_GetListMemberByPermisstionUser_Result> Ins_MemberAdmin_GetListMemberByPermisstionUser(Nullable<int> pageId, Nullable<int> rules, Nullable<int> rowStart, Nullable<int> rowEnd, Nullable<int> orderBy, Nullable<int> orderDirection, ObjectParameter totalRow)
        {
            var pageIdParameter = pageId.HasValue ?
                new ObjectParameter("PageId", pageId) :
                new ObjectParameter("PageId", typeof(int));
    
            var rulesParameter = rules.HasValue ?
                new ObjectParameter("Rules", rules) :
                new ObjectParameter("Rules", typeof(int));
    
            var rowStartParameter = rowStart.HasValue ?
                new ObjectParameter("RowStart", rowStart) :
                new ObjectParameter("RowStart", typeof(int));
    
            var rowEndParameter = rowEnd.HasValue ?
                new ObjectParameter("RowEnd", rowEnd) :
                new ObjectParameter("RowEnd", typeof(int));
    
            var orderByParameter = orderBy.HasValue ?
                new ObjectParameter("OrderBy", orderBy) :
                new ObjectParameter("OrderBy", typeof(int));
    
            var orderDirectionParameter = orderDirection.HasValue ?
                new ObjectParameter("OrderDirection", orderDirection) :
                new ObjectParameter("OrderDirection", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Ins_MemberAdmin_GetListMemberByPermisstionUser_Result>("Ins_MemberAdmin_GetListMemberByPermisstionUser", pageIdParameter, rulesParameter, rowStartParameter, rowEndParameter, orderByParameter, orderDirectionParameter, totalRow);
        }
    
        public virtual ObjectResult<Ins_MemberAdmin_GetListUser_Result> Ins_MemberAdmin_GetListUser(Nullable<int> orderBy, Nullable<int> orderDirection, Nullable<int> startRow, Nullable<int> endRow, ObjectParameter totalRow)
        {
            var orderByParameter = orderBy.HasValue ?
                new ObjectParameter("OrderBy", orderBy) :
                new ObjectParameter("OrderBy", typeof(int));
    
            var orderDirectionParameter = orderDirection.HasValue ?
                new ObjectParameter("OrderDirection", orderDirection) :
                new ObjectParameter("OrderDirection", typeof(int));
    
            var startRowParameter = startRow.HasValue ?
                new ObjectParameter("StartRow", startRow) :
                new ObjectParameter("StartRow", typeof(int));
    
            var endRowParameter = endRow.HasValue ?
                new ObjectParameter("EndRow", endRow) :
                new ObjectParameter("EndRow", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Ins_MemberAdmin_GetListUser_Result>("Ins_MemberAdmin_GetListUser", orderByParameter, orderDirectionParameter, startRowParameter, endRowParameter, totalRow);
        }
    
        public virtual ObjectResult<Ins_MemberAdmin_GetListUserAdmin_Result> Ins_MemberAdmin_GetListUserAdmin()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Ins_MemberAdmin_GetListUserAdmin_Result>("Ins_MemberAdmin_GetListUserAdmin");
        }
    
        public virtual ObjectResult<string> Ins_MemberAdmin_GetPermission(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Ins_MemberAdmin_GetPermission", userIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Ins_MemberAdmin_SaveMemberAdmin(Nullable<int> userId, string nickName, string fullName, string email, string password, string passwordSalt, Nullable<bool> isLock, Nullable<int> groupId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            var nickNameParameter = nickName != null ?
                new ObjectParameter("nickName", nickName) :
                new ObjectParameter("nickName", typeof(string));
    
            var fullNameParameter = fullName != null ?
                new ObjectParameter("fullName", fullName) :
                new ObjectParameter("fullName", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var passwordSaltParameter = passwordSalt != null ?
                new ObjectParameter("passwordSalt", passwordSalt) :
                new ObjectParameter("passwordSalt", typeof(string));
    
            var isLockParameter = isLock.HasValue ?
                new ObjectParameter("isLock", isLock) :
                new ObjectParameter("isLock", typeof(bool));
    
            var groupIdParameter = groupId.HasValue ?
                new ObjectParameter("groupId", groupId) :
                new ObjectParameter("groupId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Ins_MemberAdmin_SaveMemberAdmin", userIdParameter, nickNameParameter, fullNameParameter, emailParameter, passwordParameter, passwordSaltParameter, isLockParameter, groupIdParameter);
        }
    
        public virtual int Ins_MemberAdmin_updateTokenExp(Nullable<System.DateTime> tokenExp, Nullable<int> userId, string token)
        {
            var tokenExpParameter = tokenExp.HasValue ?
                new ObjectParameter("tokenExp", tokenExp) :
                new ObjectParameter("tokenExp", typeof(System.DateTime));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            var tokenParameter = token != null ?
                new ObjectParameter("token", token) :
                new ObjectParameter("token", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Ins_MemberAdmin_updateTokenExp", tokenExpParameter, userIdParameter, tokenParameter);
        }
    
        public virtual int Ins_MemberAdmin_updateTokenUser(Nullable<int> userId, string newTokenID, Nullable<System.DateTime> newTokenExp)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            var newTokenIDParameter = newTokenID != null ?
                new ObjectParameter("NewTokenID", newTokenID) :
                new ObjectParameter("NewTokenID", typeof(string));
    
            var newTokenExpParameter = newTokenExp.HasValue ?
                new ObjectParameter("NewTokenExp", newTokenExp) :
                new ObjectParameter("NewTokenExp", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Ins_MemberAdmin_updateTokenUser", userIdParameter, newTokenIDParameter, newTokenExpParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Ins_MemberPermission_checkPermissionPage(Nullable<int> userId, string strUrl)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            var strUrlParameter = strUrl != null ?
                new ObjectParameter("strUrl", strUrl) :
                new ObjectParameter("strUrl", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Ins_MemberPermission_checkPermissionPage", userIdParameter, strUrlParameter);
        }
    
        public virtual int Ins_MemberPermission_CloneUser(Nullable<int> userIDClone, Nullable<int> userID)
        {
            var userIDCloneParameter = userIDClone.HasValue ?
                new ObjectParameter("UserIDClone", userIDClone) :
                new ObjectParameter("UserIDClone", typeof(int));
    
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Ins_MemberPermission_CloneUser", userIDCloneParameter, userIDParameter);
        }
    
        public virtual ObjectResult<Ins_MemberPermission_getPagePermission_Result> Ins_MemberPermission_getPagePermission(Nullable<int> userId, Nullable<int> appId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            var appIdParameter = appId.HasValue ?
                new ObjectParameter("appId", appId) :
                new ObjectParameter("appId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Ins_MemberPermission_getPagePermission_Result>("Ins_MemberPermission_getPagePermission", userIdParameter, appIdParameter);
        }
    
        public virtual ObjectResult<Ins_MemberPermission_GetPermissionByUser_Result> Ins_MemberPermission_GetPermissionByUser(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Ins_MemberPermission_GetPermissionByUser_Result>("Ins_MemberPermission_GetPermissionByUser", userIdParameter);
        }
    
        public virtual ObjectResult<Ins_MemberPermission_getPermissionUserByUserId_Result> Ins_MemberPermission_getPermissionUserByUserId(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Ins_MemberPermission_getPermissionUserByUserId_Result>("Ins_MemberPermission_getPermissionUserByUserId", userIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Ins_MemberPermission_InsertPermissionMember(Nullable<int> userId, string listPage, Nullable<bool> defaultPage, Nullable<int> rule, string delimiter)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            var listPageParameter = listPage != null ?
                new ObjectParameter("listPage", listPage) :
                new ObjectParameter("listPage", typeof(string));
    
            var defaultPageParameter = defaultPage.HasValue ?
                new ObjectParameter("defaultPage", defaultPage) :
                new ObjectParameter("defaultPage", typeof(bool));
    
            var ruleParameter = rule.HasValue ?
                new ObjectParameter("rule", rule) :
                new ObjectParameter("rule", typeof(int));
    
            var delimiterParameter = delimiter != null ?
                new ObjectParameter("Delimiter", delimiter) :
                new ObjectParameter("Delimiter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Ins_MemberPermission_InsertPermissionMember", userIdParameter, listPageParameter, defaultPageParameter, ruleParameter, delimiterParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Ins_MemberPermission_UpdateRuleUser(Nullable<int> userId, Nullable<int> pageId, Nullable<int> rule, Nullable<bool> @default)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            var pageIdParameter = pageId.HasValue ?
                new ObjectParameter("pageId", pageId) :
                new ObjectParameter("pageId", typeof(int));
    
            var ruleParameter = rule.HasValue ?
                new ObjectParameter("rule", rule) :
                new ObjectParameter("rule", typeof(int));
    
            var defaultParameter = @default.HasValue ?
                new ObjectParameter("default", @default) :
                new ObjectParameter("default", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Ins_MemberPermission_UpdateRuleUser", userIdParameter, pageIdParameter, ruleParameter, defaultParameter);
        }
    
        public virtual ObjectResult<Ins_PageFunction_GetPageFunctionById_Result> Ins_PageFunction_GetPageFunctionById(Nullable<int> actionId)
        {
            var actionIdParameter = actionId.HasValue ?
                new ObjectParameter("ActionId", actionId) :
                new ObjectParameter("ActionId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Ins_PageFunction_GetPageFunctionById_Result>("Ins_PageFunction_GetPageFunctionById", actionIdParameter);
        }
    
        public virtual ObjectResult<Ins_PageFunction_InsertPage_Result> Ins_PageFunction_InsertPage(Nullable<int> parentId, string name, Nullable<int> status, string link, string linkUse, Nullable<int> funcPage, Nullable<bool> isEnable, Nullable<bool> isTarget, Nullable<int> pageType)
        {
            var parentIdParameter = parentId.HasValue ?
                new ObjectParameter("parentId", parentId) :
                new ObjectParameter("parentId", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(int));
    
            var linkParameter = link != null ?
                new ObjectParameter("link", link) :
                new ObjectParameter("link", typeof(string));
    
            var linkUseParameter = linkUse != null ?
                new ObjectParameter("linkUse", linkUse) :
                new ObjectParameter("linkUse", typeof(string));
    
            var funcPageParameter = funcPage.HasValue ?
                new ObjectParameter("FuncPage", funcPage) :
                new ObjectParameter("FuncPage", typeof(int));
    
            var isEnableParameter = isEnable.HasValue ?
                new ObjectParameter("isEnable", isEnable) :
                new ObjectParameter("isEnable", typeof(bool));
    
            var isTargetParameter = isTarget.HasValue ?
                new ObjectParameter("isTarget", isTarget) :
                new ObjectParameter("isTarget", typeof(bool));
    
            var pageTypeParameter = pageType.HasValue ?
                new ObjectParameter("pageType", pageType) :
                new ObjectParameter("pageType", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Ins_PageFunction_InsertPage_Result>("Ins_PageFunction_InsertPage", parentIdParameter, nameParameter, statusParameter, linkParameter, linkUseParameter, funcPageParameter, isEnableParameter, isTargetParameter, pageTypeParameter);
        }
    
        public virtual ObjectResult<Ins_PageFunction_ListMenu_Result> Ins_PageFunction_ListMenu(Nullable<int> groupID)
        {
            var groupIDParameter = groupID.HasValue ?
                new ObjectParameter("GroupID", groupID) :
                new ObjectParameter("GroupID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Ins_PageFunction_ListMenu_Result>("Ins_PageFunction_ListMenu", groupIDParameter);
        }
    
        public virtual ObjectResult<Ins_PageFunction_ListMenuPageForGroup_Result> Ins_PageFunction_ListMenuPageForGroup(Nullable<int> userID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Ins_PageFunction_ListMenuPageForGroup_Result>("Ins_PageFunction_ListMenuPageForGroup", userIDParameter);
        }
    
        public virtual ObjectResult<Ins_PageFunction_ListMenuUser_Result> Ins_PageFunction_ListMenuUser(Nullable<int> userID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Ins_PageFunction_ListMenuUser_Result>("Ins_PageFunction_ListMenuUser", userIDParameter);
        }
    
        public virtual int Ins_Permission_Delete(Nullable<int> userID, Nullable<int> pageID, Nullable<int> type)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var pageIDParameter = pageID.HasValue ?
                new ObjectParameter("PageID", pageID) :
                new ObjectParameter("PageID", typeof(int));
    
            var typeParameter = type.HasValue ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Ins_Permission_Delete", userIDParameter, pageIDParameter, typeParameter);
        }
    
        [DbFunction("MetroMembershipEntities", "Ins_SplitToIntTable")]
        public virtual IQueryable<Nullable<int>> Ins_SplitToIntTable(string @string, string delimiter)
        {
            var stringParameter = @string != null ?
                new ObjectParameter("String", @string) :
                new ObjectParameter("String", typeof(string));
    
            var delimiterParameter = delimiter != null ?
                new ObjectParameter("Delimiter", delimiter) :
                new ObjectParameter("Delimiter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Nullable<int>>("[MetroMembershipEntities].[Ins_SplitToIntTable](@String, @Delimiter)", stringParameter, delimiterParameter);
        }
    
        public virtual int Ins_LogActionAdmin_GetLockedLogByTime(Nullable<System.DateTime> fromTime, Nullable<System.DateTime> toTime, Nullable<int> actionID)
        {
            var fromTimeParameter = fromTime.HasValue ?
                new ObjectParameter("FromTime", fromTime) :
                new ObjectParameter("FromTime", typeof(System.DateTime));
    
            var toTimeParameter = toTime.HasValue ?
                new ObjectParameter("ToTime", toTime) :
                new ObjectParameter("ToTime", typeof(System.DateTime));
    
            var actionIDParameter = actionID.HasValue ?
                new ObjectParameter("ActionID", actionID) :
                new ObjectParameter("ActionID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Ins_LogActionAdmin_GetLockedLogByTime", fromTimeParameter, toTimeParameter, actionIDParameter);
        }
    }
}
