//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesObject.Entities.MetroMembershipEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionAdmin
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> ActionTypeId { get; set; }
        public string Description { get; set; }
    }
}
