//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminConfigData
    {
        public int KeyID { get; set; }
        public int AdminID { get; set; }
        public string KeyName { get; set; }
        public string KeyConfig { get; set; }
        public string Note { get; set; }
    }
}
