//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesObject.Entities.UserEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class KiotPromotion
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> KiotID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<decimal> PricePromotion { get; set; }
        public Nullable<System.DateTime> BeginPromotion { get; set; }
        public Nullable<System.DateTime> EndPromotion { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    }
}
