//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesObject.Entities.UserEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogCardOpenGiftBox
    {
        public int ID { get; set; }
        public Nullable<int> UserId { get; set; }
        public string TranId { get; set; }
        public Nullable<int> ItemGameUserId { get; set; }
        public string Serial { get; set; }
        public string PinCode { get; set; }
        public Nullable<int> CardType { get; set; }
        public Nullable<int> CardAmount { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> Result { get; set; }
        public string PartnerMessage { get; set; }
        public Nullable<int> MinValue { get; set; }
        public Nullable<int> MaxValue { get; set; }
    }
}
