//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesObject.Entities.UserEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogCreditTran
    {
        public int ID { get; set; }
        public Nullable<int> AgentPPID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<decimal> CurrentCoin { get; set; }
        public Nullable<decimal> CoinTrans { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<int> Status { get; set; }
        public string txn_id { get; set; }
        public string Token { get; set; }
        public string CardType { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> ReceiveGoldDate { get; set; }
        public Nullable<int> TransactionType { get; set; }
        public Nullable<int> ChannelID { get; set; }
        public Nullable<int> PlatformId { get; set; }
        public string VersionGame { get; set; }
    }
}
