//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesObject.Entities.UserEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogTransactionGold
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<decimal> CurrentValue { get; set; }
        public Nullable<decimal> ChangeValue { get; set; }
        public Nullable<int> AdminId { get; set; }
        public Nullable<int> LogTypeId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> IdHistory { get; set; }
        public Nullable<int> ClientTarget { get; set; }
        public string Description { get; set; }
    }
}
