//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using EntitiesObject.Entities.MetroUserEntities;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MetroUserEntities : DbContext
    {
        public MetroUserEntities()
            : base("name=MetroUserEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Article> Articles { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<FastNew> FastNews { get; set; }
    
        public virtual int Ins_Article_Save(string title, Nullable<int> categorieID, string newsContent, string imageArticle, Nullable<int> status, Nullable<int> isComment, string shortDescription, string seoLink, string createBy, Nullable<int> iD)
        {
            var titleParameter = title != null ?
                new ObjectParameter("Title", title) :
                new ObjectParameter("Title", typeof(string));
    
            var categorieIDParameter = categorieID.HasValue ?
                new ObjectParameter("CategorieID", categorieID) :
                new ObjectParameter("CategorieID", typeof(int));
    
            var newsContentParameter = newsContent != null ?
                new ObjectParameter("NewsContent", newsContent) :
                new ObjectParameter("NewsContent", typeof(string));
    
            var imageArticleParameter = imageArticle != null ?
                new ObjectParameter("ImageArticle", imageArticle) :
                new ObjectParameter("ImageArticle", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(int));
    
            var isCommentParameter = isComment.HasValue ?
                new ObjectParameter("IsComment", isComment) :
                new ObjectParameter("IsComment", typeof(int));
    
            var shortDescriptionParameter = shortDescription != null ?
                new ObjectParameter("ShortDescription", shortDescription) :
                new ObjectParameter("ShortDescription", typeof(string));
    
            var seoLinkParameter = seoLink != null ?
                new ObjectParameter("SeoLink", seoLink) :
                new ObjectParameter("SeoLink", typeof(string));
    
            var createByParameter = createBy != null ?
                new ObjectParameter("CreateBy", createBy) :
                new ObjectParameter("CreateBy", typeof(string));
    
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Ins_Article_Save", titleParameter, categorieIDParameter, newsContentParameter, imageArticleParameter, statusParameter, isCommentParameter, shortDescriptionParameter, seoLinkParameter, createByParameter, iDParameter);
        }
    
        public virtual ObjectResult<Out_Categories_Get_Result> Out_Categories_Get()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Out_Categories_Get_Result>("Out_Categories_Get");
        }
    }
}
