//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesObject.Entities.EventManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventPromotion
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public Nullable<int> EventId { get; set; }
        public Nullable<int> Type { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> BeginTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<System.DateTime> BeginDisplayTime { get; set; }
        public Nullable<System.DateTime> EndDisplayTime { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string ConfigData { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> RunOn { get; set; }
        public Nullable<int> IsDelete { get; set; }
    }
}
