//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesObject.Entities.EventManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMission_Top
    {
        public int UserID { get; set; }
        public int MissionID { get; set; }
        public string Description { get; set; }
        public System.DateTime DateCreate { get; set; }
        public Nullable<System.DateTime> DateInsert { get; set; }
    }
}
