//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesObject.Entities.KaraSysEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public int ID { get; set; }
        public string RoomCode { get; set; }
        public Nullable<int> RoomTypeID { get; set; }
        public string Title { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> CurrentRoomLogID { get; set; }
        public Nullable<int> FloorID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
