//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyRegisterLog
    {
        public int ID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> Package { get; set; }
        public Nullable<int> Method { get; set; }
        public string ContactMail { get; set; }
        public string ContactName { get; set; }
        public string ContactAddress { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Language { get; set; }
    }
}
