//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using EntitiesObject.Entities.WebEntities;

    public partial class WebEntities : DbContext
    {
        public WebEntities()
            : base("name=WebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Article> Articles { get; set; }
        public virtual DbSet<CategoryArticle> CategoryArticles { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Plain> Plains { get; set; }
        public virtual DbSet<Slogan> Slogans { get; set; }
        public virtual DbSet<Stat> Stats { get; set; }
        public virtual DbSet<CategoryPortfolio> CategoryPortfolios { get; set; }
        public virtual DbSet<Portfolio> Portfolios { get; set; }
        public virtual DbSet<Config> Configs { get; set; }
        public virtual DbSet<Work> Works { get; set; }
        public virtual DbSet<CategoryWork> CategoryWorks { get; set; }
    
        public virtual int Out_Article_Save(Nullable<int> id, string title, string image, string contentBody, Nullable<int> categoryId)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var titleParameter = title != null ?
                new ObjectParameter("Title", title) :
                new ObjectParameter("Title", typeof(string));
    
            var imageParameter = image != null ?
                new ObjectParameter("Image", image) :
                new ObjectParameter("Image", typeof(string));
    
            var contentBodyParameter = contentBody != null ?
                new ObjectParameter("ContentBody", contentBody) :
                new ObjectParameter("ContentBody", typeof(string));
    
            var categoryIdParameter = categoryId.HasValue ?
                new ObjectParameter("CategoryId", categoryId) :
                new ObjectParameter("CategoryId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Out_Article_Save", idParameter, titleParameter, imageParameter, contentBodyParameter, categoryIdParameter);
        }
    
        public virtual int Out_Contact_Save(string name, string phone, string email, string messenger)
        {
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("Phone", phone) :
                new ObjectParameter("Phone", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var messengerParameter = messenger != null ?
                new ObjectParameter("Messenger", messenger) :
                new ObjectParameter("Messenger", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Out_Contact_Save", nameParameter, phoneParameter, emailParameter, messengerParameter);
        }
    
        public virtual ObjectResult<Out_Article_GetListData_Result> Out_Article_GetListData(Nullable<int> rowStart, Nullable<int> rowEnd, Nullable<int> orderBy, Nullable<bool> isDescending, ObjectParameter totalRow)
        {
            var rowStartParameter = rowStart.HasValue ?
                new ObjectParameter("RowStart", rowStart) :
                new ObjectParameter("RowStart", typeof(int));
    
            var rowEndParameter = rowEnd.HasValue ?
                new ObjectParameter("RowEnd", rowEnd) :
                new ObjectParameter("RowEnd", typeof(int));
    
            var orderByParameter = orderBy.HasValue ?
                new ObjectParameter("OrderBy", orderBy) :
                new ObjectParameter("OrderBy", typeof(int));
    
            var isDescendingParameter = isDescending.HasValue ?
                new ObjectParameter("IsDescending", isDescending) :
                new ObjectParameter("IsDescending", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Out_Article_GetListData_Result>("Out_Article_GetListData", rowStartParameter, rowEndParameter, orderByParameter, isDescendingParameter, totalRow);
        }
    
        public virtual ObjectResult<Out_Contact_GetListData_Result> Out_Contact_GetListData(Nullable<int> rowStart, Nullable<int> rowEnd, Nullable<int> orderBy, Nullable<bool> isDescending, ObjectParameter totalRow)
        {
            var rowStartParameter = rowStart.HasValue ?
                new ObjectParameter("RowStart", rowStart) :
                new ObjectParameter("RowStart", typeof(int));
    
            var rowEndParameter = rowEnd.HasValue ?
                new ObjectParameter("RowEnd", rowEnd) :
                new ObjectParameter("RowEnd", typeof(int));
    
            var orderByParameter = orderBy.HasValue ?
                new ObjectParameter("OrderBy", orderBy) :
                new ObjectParameter("OrderBy", typeof(int));
    
            var isDescendingParameter = isDescending.HasValue ?
                new ObjectParameter("IsDescending", isDescending) :
                new ObjectParameter("IsDescending", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Out_Contact_GetListData_Result>("Out_Contact_GetListData", rowStartParameter, rowEndParameter, orderByParameter, isDescendingParameter, totalRow);
        }
    
        public virtual ObjectResult<Out_CategoryArticle_GetList_Result> Out_CategoryArticle_GetList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Out_CategoryArticle_GetList_Result>("Out_CategoryArticle_GetList");
        }
    
        public virtual ObjectResult<Out_Article_GetById_Result> Out_Article_GetById(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Out_Article_GetById_Result>("Out_Article_GetById", idParameter);
        }
    
        public virtual ObjectResult<Out_Slogan_Get_Result> Out_Slogan_Get()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Out_Slogan_Get_Result>("Out_Slogan_Get");
        }
    
        public virtual ObjectResult<Out_Article_GetByTextId_Result> Out_Article_GetByTextId(string textId)
        {
            var textIdParameter = textId != null ?
                new ObjectParameter("textId", textId) :
                new ObjectParameter("textId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Out_Article_GetByTextId_Result>("Out_Article_GetByTextId", textIdParameter);
        }
    
        public virtual int Out_Portfolio_Save(Nullable<int> id, string name, string avatar, string about, Nullable<int> categoryId, string linkWeb, string linkProfile)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var avatarParameter = avatar != null ?
                new ObjectParameter("Avatar", avatar) :
                new ObjectParameter("Avatar", typeof(string));
    
            var aboutParameter = about != null ?
                new ObjectParameter("About", about) :
                new ObjectParameter("About", typeof(string));
    
            var categoryIdParameter = categoryId.HasValue ?
                new ObjectParameter("CategoryId", categoryId) :
                new ObjectParameter("CategoryId", typeof(int));
    
            var linkWebParameter = linkWeb != null ?
                new ObjectParameter("LinkWeb", linkWeb) :
                new ObjectParameter("LinkWeb", typeof(string));
    
            var linkProfileParameter = linkProfile != null ?
                new ObjectParameter("LinkProfile", linkProfile) :
                new ObjectParameter("LinkProfile", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Out_Portfolio_Save", idParameter, nameParameter, avatarParameter, aboutParameter, categoryIdParameter, linkWebParameter, linkProfileParameter);
        }
    
        public virtual ObjectResult<Out_Portfolio_GetById_Result> Out_Portfolio_GetById(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Out_Portfolio_GetById_Result>("Out_Portfolio_GetById", idParameter);
        }
    
        public virtual ObjectResult<Out_Portfolio_GetList_Result> Out_Portfolio_GetList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Out_Portfolio_GetList_Result>("Out_Portfolio_GetList");
        }
    
        public virtual ObjectResult<Out_Portfolio_GetListData_Result> Out_Portfolio_GetListData(Nullable<int> rowStart, Nullable<int> rowEnd, Nullable<int> orderBy, Nullable<bool> isDescending, ObjectParameter totalRow)
        {
            var rowStartParameter = rowStart.HasValue ?
                new ObjectParameter("RowStart", rowStart) :
                new ObjectParameter("RowStart", typeof(int));
    
            var rowEndParameter = rowEnd.HasValue ?
                new ObjectParameter("RowEnd", rowEnd) :
                new ObjectParameter("RowEnd", typeof(int));
    
            var orderByParameter = orderBy.HasValue ?
                new ObjectParameter("OrderBy", orderBy) :
                new ObjectParameter("OrderBy", typeof(int));
    
            var isDescendingParameter = isDescending.HasValue ?
                new ObjectParameter("IsDescending", isDescending) :
                new ObjectParameter("IsDescending", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Out_Portfolio_GetListData_Result>("Out_Portfolio_GetListData", rowStartParameter, rowEndParameter, orderByParameter, isDescendingParameter, totalRow);
        }
    
        public virtual ObjectResult<Out_Portfolio_GetListCategoryPortfolio_Result> Out_Portfolio_GetListCategoryPortfolio()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Out_Portfolio_GetListCategoryPortfolio_Result>("Out_Portfolio_GetListCategoryPortfolio");
        }
    
        public virtual ObjectResult<Out_Article_GetByCategoryId_Result> Out_Article_GetByCategoryId(Nullable<int> categoryId)
        {
            var categoryIdParameter = categoryId.HasValue ?
                new ObjectParameter("CategoryId", categoryId) :
                new ObjectParameter("CategoryId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Out_Article_GetByCategoryId_Result>("Out_Article_GetByCategoryId", categoryIdParameter);
        }
    
        public virtual ObjectResult<Out_Work_GetById_Result> Out_Work_GetById(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Out_Work_GetById_Result>("Out_Work_GetById", idParameter);
        }
    
        public virtual ObjectResult<Out_Work_GetByTextId_Result> Out_Work_GetByTextId(string textId)
        {
            var textIdParameter = textId != null ?
                new ObjectParameter("textId", textId) :
                new ObjectParameter("textId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Out_Work_GetByTextId_Result>("Out_Work_GetByTextId", textIdParameter);
        }
    
        public virtual ObjectResult<Out_Work_GetListData_Result> Out_Work_GetListData(Nullable<int> rowStart, Nullable<int> rowEnd, Nullable<int> orderBy, Nullable<bool> isDescending, ObjectParameter totalRow)
        {
            var rowStartParameter = rowStart.HasValue ?
                new ObjectParameter("RowStart", rowStart) :
                new ObjectParameter("RowStart", typeof(int));
    
            var rowEndParameter = rowEnd.HasValue ?
                new ObjectParameter("RowEnd", rowEnd) :
                new ObjectParameter("RowEnd", typeof(int));
    
            var orderByParameter = orderBy.HasValue ?
                new ObjectParameter("OrderBy", orderBy) :
                new ObjectParameter("OrderBy", typeof(int));
    
            var isDescendingParameter = isDescending.HasValue ?
                new ObjectParameter("IsDescending", isDescending) :
                new ObjectParameter("IsDescending", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Out_Work_GetListData_Result>("Out_Work_GetListData", rowStartParameter, rowEndParameter, orderByParameter, isDescendingParameter, totalRow);
        }
    
        public virtual int Out_Work_Save(Nullable<int> id, string title, string image, string contentBody, Nullable<int> categoryId)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var titleParameter = title != null ?
                new ObjectParameter("Title", title) :
                new ObjectParameter("Title", typeof(string));
    
            var imageParameter = image != null ?
                new ObjectParameter("Image", image) :
                new ObjectParameter("Image", typeof(string));
    
            var contentBodyParameter = contentBody != null ?
                new ObjectParameter("ContentBody", contentBody) :
                new ObjectParameter("ContentBody", typeof(string));
    
            var categoryIdParameter = categoryId.HasValue ?
                new ObjectParameter("CategoryId", categoryId) :
                new ObjectParameter("CategoryId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Out_Work_Save", idParameter, titleParameter, imageParameter, contentBodyParameter, categoryIdParameter);
        }
    
        public virtual ObjectResult<Out_CategoryWork_GetList_Result> Out_CategoryWork_GetList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Out_CategoryWork_GetList_Result>("Out_CategoryWork_GetList");
        }
    
        public virtual ObjectResult<Out_Config_GetByKey_Result> Out_Config_GetByKey(string keyConfig)
        {
            var keyConfigParameter = keyConfig != null ?
                new ObjectParameter("KeyConfig", keyConfig) :
                new ObjectParameter("KeyConfig", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Out_Config_GetByKey_Result>("Out_Config_GetByKey", keyConfigParameter);
        }
    
        public virtual int Out_Config_SaveByKey(string key, string value)
        {
            var keyParameter = key != null ?
                new ObjectParameter("Key", key) :
                new ObjectParameter("Key", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("Value", value) :
                new ObjectParameter("Value", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Out_Config_SaveByKey", keyParameter, valueParameter);
        }
    
        public virtual ObjectResult<Out_Work_GetByCategoryId_Result> Out_Work_GetByCategoryId(Nullable<int> categoryId)
        {
            var categoryIdParameter = categoryId.HasValue ?
                new ObjectParameter("CategoryId", categoryId) :
                new ObjectParameter("CategoryId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Out_Work_GetByCategoryId_Result>("Out_Work_GetByCategoryId", categoryIdParameter);
        }
    
        public virtual ObjectResult<Out_Article_GetArticleBlog_Result> Out_Article_GetArticleBlog(Nullable<int> categoryId, Nullable<int> startIndex, Nullable<int> pageLength, ObjectParameter totalRow)
        {
            var categoryIdParameter = categoryId.HasValue ?
                new ObjectParameter("CategoryId", categoryId) :
                new ObjectParameter("CategoryId", typeof(int));
    
            var startIndexParameter = startIndex.HasValue ?
                new ObjectParameter("StartIndex", startIndex) :
                new ObjectParameter("StartIndex", typeof(int));
    
            var pageLengthParameter = pageLength.HasValue ?
                new ObjectParameter("PageLength", pageLength) :
                new ObjectParameter("PageLength", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Out_Article_GetArticleBlog_Result>("Out_Article_GetArticleBlog", categoryIdParameter, startIndexParameter, pageLengthParameter, totalRow);
        }
    }
}
